metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 15s
  configs:
    - name: prometheus_scrape
      scrape_configs:
        - job_name: 'app_metrics_example_job'
          static_configs:
            - targets: [host.docker.internal:5000]
      remote_write:
        - url: https://metrics.cockpit.fr-par.scw.cloud/api/v1/push
          headers:
            "X-Token": ${SCW_API_KEY}
            
logs:
  positions_directory: /tmp/positions/
  configs:
    - name: scw
      clients:
        - url: https://logs.cockpit.fr-par.scw.cloud/loki/api/v1/push
          tenant_id: ${SCW_API_KEY}
      scrape_configs:
        - job_name: appmetrics_logs
          static_configs:
            - targets: [host.docker.internal]
              labels:
                job: varlogs
                __path__: /var/log/docker_logs/**/*.log
                