metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 5s
  configs:
    - name: prometheus_scrape
      scrape_configs:
        - job_name: 'prometheus_metrics'
          static_configs:
            - targets: [host.docker.internal:5149]
      remote_write:
        - url: https://metrics.cockpit.fr-par.scw.cloud/api/v1/push
          headers:
            "X-Token": Chqsu3DgNr0cdG5cP8rGdeMWvQGqRku9hGZbj8qNEWUWoFPqXf3Yxz2cnUq7EGlm