metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 10s
  configs:
    - name: prometheus_scrape
      scrape_configs:
        - job_name: 'prometheus_metrics'
          static_configs:
            - targets: [host.docker.internal:5000]
      remote_write:
        - url: https://metrics.cockpit.fr-par.scw.cloud/api/v1/push
          headers:
            "X-Token": Chqsu3DgNr0cdG5cP8rGdeMWvQGqRku9hGZbj8qNEWUWoFPqXf3Yxz2cnUq7EGlm
            
logs:
  positions_directory: /tmp/positions/
  configs:
    - name: scw
      clients:
        - url: https://logs.cockpit.fr-par.scw.cloud/loki/api/v1/push
          tenant_id: <Scaleway token id>
      scrape_configs:
        - job_name: appmetrics_logs
          static_configs:
            - targets: [host.docker.internal]
              labels:
                job: varlogs
                __path__: /var/log/dockerlogs/**/*.log
                