version: "3"
services:
  agent:
    image: grafana/agent:latest
    restart: always
    ports:
      - "9412:9412"
    volumes:
      - "./config.yaml:/etc/agent-config/agent.yaml:ro"
      - "/:/host/root:ro"
      - "/tmp/agent:/etc/agent"
    entrypoint:
      - /bin/grafana-agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
    network_mode: "host"
    pid: "host"